services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres
        environment:
            - DATABASE_URL=postgres://user:password@postgres:5432/db
            - PORT=3000
            - NODE_ENV=production
        ports:
            - '8787:3000'
    
    postgres:
        image: postgres
        ports:
            - "35000:5432"
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=DB
